# Generated by Django 6.0.2 on 2026-04-17 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_add_message_and_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupInformation',
            fields=[
                ('pickup_information_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_method', models.CharField(max_length=255)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('buyers_only', 'Buyers Only'), ('private', 'Private')], default='public', max_length=20)),
            ],
            options={
                'db_table': 'pickup_information',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.listing')),
            ],
            options={
                'db_table': 'service',
            },
            bases=('backend.listing',),
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'managed': False, 'ordering': ['-created_at', '-listing_id']},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.listing')),
                ('pickup_information', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='backend.pickupinformation')),
            ],
            options={
                'db_table': 'product',
            },
            bases=('backend.listing',),
        ),
    ]
