# Generated by Django 6.0.2 on 2026-04-12 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_marketplace_seed_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'managed': False, 'ordering': ['-created_at', '-listing_id']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='item_ptr',
            new_name='listing_ptr',
        ),
        migrations.AddField(
            model_name='service',
            name='listing_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.listing'),
            preserve_default=False,
        ),
    ]
