# Generated by Django 6.0.2 on 2026-04-14 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_add_message_and_defaults'),
        ('backend', '0003_alter_listing_options_and_more'),
    ]

    operations = [
    ]
