# Generated by Django 6.0.2 on 2026-05-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_user_role'),
        ('marketplace', '0002_userprofile'),
    ]

    operations = [
    ]
